title: Nimish Tembhurne
logo: assets/profile.jpg
# description: Data Scientist | Generative AI Developer
theme: jekyll-theme-minimal
# show_downloads: true
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
